services:
  postgres:
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    ports:
      - "${REDIS_PORT}:6379"

  app:
    build:
      target: dev
    environment:
      LOG_LEVEL: debug
    volumes:
      - .:/app
      - /app/.venv
